// <auto-generated />
using ExploreCalifornia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExploreCalifornia.Migrations
{
    [DbContext(typeof(DiaryContext))]
    [Migration("20190309145210_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExploreCalifornia.Models.Entry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntryTitle");

                    b.Property<string>("entryDescription");

                    b.HasKey("EntryID");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("ExploreCalifornia.Models.PainDetails", b =>
                {
                    b.Property<int>("PainDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntryID");

                    b.Property<string>("Test");

                    b.HasKey("PainDetailsID");

                    b.HasIndex("EntryID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ExploreCalifornia.Models.PainDetails", b =>
                {
                    b.HasOne("ExploreCalifornia.Models.Entry", "Entry")
                        .WithMany("Areas")
                        .HasForeignKey("EntryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
