// <auto-generated />
using System;
using ExploreCalifornia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExploreCalifornia.Migrations
{
    [DbContext(typeof(DiaryContext))]
    partial class DiaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExploreCalifornia.Models.Area", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EntryID");

                    b.Property<string>("Test");

                    b.HasKey("AreaID");

                    b.HasIndex("EntryID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ExploreCalifornia.Models.Entry", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntryTitle");

                    b.Property<string>("entryDescription");

                    b.HasKey("EntryID");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("ExploreCalifornia.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IncludesMeals");

                    b.Property<int>("Length");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<string>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Tour");
                });

            modelBuilder.Entity("ExploreCalifornia.Models.Area", b =>
                {
                    b.HasOne("ExploreCalifornia.Models.Entry")
                        .WithMany("Areas")
                        .HasForeignKey("EntryID");
                });
#pragma warning restore 612, 618
        }
    }
}
